baseURL: "https://one-day.dev/"
languageCode: "ko-kr"
title: "One day dev"
theme: "novela"
pygmentsstyle: 'monokai'
paginate: 6
taxonomies:
  author: authors
googleAnalytics: UA-157925958-1
params:
  locale: "ko_KR"
  description: "딱 하루, 낯선 회사에서 일하고 관찰하고 기록합니다"
  seo:
    default_image: "/images/og-image.jpg"
  title: "One day dev"
